### ISSUE TITLE
Breaking Speaker In Creative Causes Client Crash on Dedicated Server - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Stumblinbear/BetterRecords#54] opened 2018-01-15 19:47 UTC
Code Right After Crash 
https://gist.github.com/P3rf3ctXZer0/65d17669bb7728cec8dcd853747f147f

Crash Log
https://gist.github.com/P3rf3ctXZer0/4227a668b447392d5a82af4c23e2482f

Client Log
https://gist.github.com/P3rf3ctXZer0/44b9ce7db580042534908c4e9ee14850

Latest
https://gist.github.com/P3rf3ctXZer0/a4fb96b408e7e1628e9325617d017ac5

Server  Latest 
https://gist.github.com/P3rf3ctXZer0/6d6a058059ce7b5d6cef9d4fb7901652

**Comment by NicholasFeldman** [comment] 2018-01-15 22:26
I'm unable to reproduce this. Please provide the information available in the Issue template:
```
BetterRecords: `version`  
Forge: `version`

# Issue
Describe the problem here

# Steps to Reproduce
1.
2.
3. 

Link to crash log: <Preferably Gist or Pastebin> 
```

Also, it looks like you're using FoamFix, try removing it and let me know if the issue still occurs.

**Comment by P3rf3ctXZer0** [comment] 2018-01-15 22:40
Okay. I will make a video when I get a chance. For the time being I just disabled the recipe XD

**Comment by P3rf3ctXZer0** [comment] 2018-01-15 22:42
OH I should specify it only occurs on a dedicated server not single player.

**Comment by NicholasFeldman** [comment] 2018-01-20 21:50
Transferred issue to new repository

**Closed by NicholasFeldman** 2018-01-20 21:50 UTC
Labels: Bug
