### ISSUE TITLE
Crash on server when right-clicking Laser with Speaker Wire [1.7.10]

### ISSUE THREAD

**Issue by InuYasha86000** [Stumblinbear/BetterRecords#3] opened 2016-07-24 07:29 UTC
I tried to right-click a laser with a speaker wire to attach it to the record player on my test server but the server crashed:
`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/24/16 12:16 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.codingforcookies.betterrecords.src.items.BlockLazer.func_149727_a(BlockLazer.java:83)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:465)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.57
	Plugins: SpecialHeads, Essentials, Vault, ChatColor, EssentialsSpawn, GroupManager, MassiveCore, Multiverse-Core, CreativeGates, GriefPrevention
	Disabled Plugins: 
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716217056 bytes (683 MB) / 2100183040 bytes (2002 MB) up to 4242669568 bytes (4046 MB)
	JVM Flags: 4 total; -Xms2048m -Xmx4096m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 164 mods loaded, 154 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10-1614-server.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10-1614-server.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	securitycraft{v1.8.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.1.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.4-114.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
	UCHIJAAAA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.7.10.jar) 
	UCHIJAAAA	BedCraftAndBeyond{${version}} [BedCraft and Beyond] (bedcraftbeyond-1.7.10-1.0.5a.jar) 
	UCHIJAAAA	betterrecords{@VERSION@} [Better Records] (BetterRecords-1.7.10-1.2.0.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	Forestry{4.2.13.61} [Forestry for Minecraft] (forestry_1.7.10-4.2.13.61.jar) 
	UCHIJAAAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJAAAA	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	CartLivery{0.11.1} [Cart Livery] (CartLivery-1.7.10-0.11.1.jar) 
	UCHIJAAAA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHIJAAAA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar) 
	UCHIJAAAA	christmastrees{1.0} [Decoratable Christmas Trees Mod] (christmastrees-1.0.jar) 
	UCHIJAAAA	CLG{2.0.1} [Compact Lava Generator] (CLG-2.0.1.jar) 
	UCHIJAAAA	ColouredTorches{1.7.10-1.1} [Coloured Torches] (ColouredTorches-1.7.10-1.2.1.jar) 
	UCHIJAAAA	complexcrops{v3} [Complex Crops] (ComplexCrops-v3-1.7.10.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	customsteveserver{1.1.0Beta} [CustomSteveServer] (CustomSteve_Server1710110Beta_Forge.jar) 
	UCHIJAAAA	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10-1.1.2.41.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.2_1.7.10.jar) 
	UCHIJAAAA	props{2.3.2} [Decocraft] (Decocraft-2.3.2_1.7.10.jar) 
	UCHIJAAAA	decorativemarble{Beta 1.1710.3} [Decorative Marble] (decorativemarble-1.1710.3.jar) 
	UCHIJAAAA	decorativechimney{Beta 1.1710.3} [Decorative Chimney] (decorativechimney-1.1710.3.jar) 
	UCHIJAAAA	DescriptionTags{1.0} [Description Tags] (DescriptionTags-1.0-1.7.10.jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAA	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) 
	UCHIJAAAA	elementalcreepers{4.3.0} [Elemental Creepers] (Elemental Creepers-universal_1.7.10-4.3.0.jar) 
	UCHIJAAAA	endercompass{1.2} [Ender Compass] (EnderCompass-1.7.10-1.2.jar) 
	UCHIJAAAA	extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJAAAA	fc{0.3.3} [FloorBallCraft] (fc-1.7.10-2.0.1.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	flashlight{ï¿½{version}} [Flashlight Mod] (Flashlight-1.7.10-1.0.jar) 
	UCHIJAAAA	FloodLights{1.2.1-134} [Flood Lights] (FloodLights-1.7.10-1.2.1-134.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
	UCHIJAAAA	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UCHIJAAAA	helpfulvillagers{1.4.0b5} [Helpful Villagers] (helpfulvillagers-1.7.10-1.4.0b5.jar) 
	UCHIJAAAA	IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
	UCHIJAAAA	immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	ironchestminecarts{1.0.3} [Iron Chest Minecarts] (IronChestMinecarts-1.0.3.jar) 
	UCHIJAAAA	irontank{1.0.1 build @BUILD@} [Iron Tanks] (irontank-1.7.10-1.0.1.50.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MoarSigns{1.2.4} [MoarSigns] (MoarSigns-1.7.10-1.2.4.jar) 
	UCHIJAAAA	mobeds{0.0.2} [Mo' Beds] (MoBeds-1.7.10-0.0.2-universal.jar) 
	UCHIJAAAA	modelcitizens{1.0.1} [Model Citizens] (ModelCitizens-mc1.7.10-1.0.1.jar) 
	UCHIJAAAA	Monoblocks{1.10.30} [§1M§2o§3n§4o§5b§6l§7o§8c§9k§as] (Monoblocks-1.10.30.jar) 
	UCHIJAAAA	MonoblocksMultipart{1.10.30} [MonoblocksMultipart] (Monoblocks-1.10.30.jar) 
	UCHIJAAAA	redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) 
	UCHIJAAAA	redgear_morebackpacks{2.2.2} [More Backpacks] (More Backpacks-1.7.10-2.2.2.jar) 
	UCHIJAAAA	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-28.jar) 
	UCHIJAAAA	MorePistons{2.0.0} [More Pistons] (MorePistons-2.0.0-1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	networksmanager{9.3R} [Networks Manager] (Networks Manager-9.3R.jar) 
	UCHIJAAAA	openfm{0.1.0.35} [OpenFM] (OpenFM-1.7.10-0.1.0-35.jar) 
	UCHIJAAAA	PlaceableTools{1.2.0.33} [PlaceableTools] (PlaceableTools-1.7.10-1.2.0.33.jar) 
	UCHIJAAAA	PowerConverters{1.7.10_3.3.0} [Power Converters] (PowerConverters-1.7.10_3.3.0-jenkins.77_unofficial.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCHIJAAAA	railcraft_cos{1.7.2} [Railcraft Cosmetic Additions] (Railcraft_Cosmetics-1.7.10-v1.7.2.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92 (1).jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	rfwindmill{0.7c} [RF Windmill] (rfwindmill-1.7.10-0.7c.jar) 
	UCHIJAAAA	roadstuff{1.0.0} [Road Stuff] (RoadStuff-mc1.7.10-1.0.0.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	SimpleLabels{@VERSION@} [SimpleLabels] (SimpleLabels-1.7.10-1.0-9.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	StainedEnderTables{1.0.4} [Stained Ender Tables] (StainedEnderTables-1.7.10-1.0.4.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.0} [Storage Drawers] (StorageDrawers-1.7.10-1.10.0.jar) 
	UCHIJAAAA	StorageDrawersBop{1.7.10-1.1.1} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar) 
	UCHIJAAAA	StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.2.jar) 
	UCHIJAAAA	StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.2.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
	UCHIJAAAA	supertramp{1.0.0} [Supertramp] (supertramp-1.0.0.jar) 
	UCHIJAAAA	thecoloredblocksmod{v1.3} [thecoloredblocksmod] (TheColoredBlocksMod-v1.3-mc1.7.10.jar) 
	UCHIJAAAA	kitchen{1.3.19} [The Kitchen Mod] (TheKitchenMod-1.3.19-1.7.2-10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	TownBuilder{1.0.0-Build8} [Town Builder] (Town-Builder-1.0.0-Build8.jar) 
	UCHIJAAAA	aziasvendingmachine{Vending Machines Revamped} [Vending Machines Revamped] (VendingMachinesRevamped_1.1.0_1.7.10.jar) 
	UCHIJAAAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
	UCHIJAAAA	woodstuff{1.3.2} [WoodStuff] (WoodStuff-1.3.2.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	zoom{1.0.1} [Zoom] (Zoom-MC1.7.10-1.0.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.4-114
	ThermalExpansion: -[1.7.10]4.1.2-240
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.0-171
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 30; [EntityPlayerMP['InuYasha86000'/49, l='world', x=-43.53, y=65.00, z=-14.47](InuYasha86000 at -43.53212907064996,65.0,-14.474322170018294)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)`

This was running on a Thermos server 1.7.10-1614

Hopefully this is an easy fix.

**Comment by AngrySoundTech** [comment] 2016-08-17 02:39
Be aware that Thermos changes some of the behavior of Forge, and can cause unexpected things to happen. I'll look into this and attempt to replicate it under different server environments.

**Comment by Borlea** [comment] 2016-08-17 03:59
@AngrySoundTech This was a bug I accidently created when updating it. Sadly the guy who updated it fully to 1.10 did not fix i t

**Comment by InuYasha86000** [comment] 2016-08-17 04:13
Someone had found that if you took the Lazer file from the 1.1.9 and put it into the 1.2.0 file it worked no problem in multiplayer.

**Comment by AngrySoundTech** [comment] 2016-08-17 17:38
From the commit history here, this bug was introduced in af9eb7f, [in this section here](https://github.com/Stumblinbear/BetterRecords/blob/af9eb7fc76d58c75116219b63b07b4c0c3bf8903/src/main/java/com/codingforcookies/betterrecords/src/items/BlockLazer.java#L68-L86).

I'll start a fork for continued 1.7.10 support/hotfixes from a4de667 and fix the issue there.

Also note that this bug does not seem to be present in the latest commit for 1.8.9, so it only needs a hotfix for 1.7.10

**Comment by AngrySoundTech** [comment] 2016-08-17 17:58
Is the current released version's source not under version control? I checked out a4de667 and was not able to reproduce the issue.

**Comment by Borlea** [comment] 2016-08-17 18:09
if anyone really cares its this line
https://github.com/Stumblinbear/BetterRecords/commit/af9eb7fc76d58c75116219b63b07b4c0c3bf8903#diff-4b49451f26a309e26c02e09753ba1dc8R83
I'm grabbing the Minecraft instance within the server.. just mess around with world.isRemote, and I also suggest changing it to player.addChatMessage

**Comment by Acdrybones** [comment] 2016-08-20 20:32
You got enough mods?

**Comment by AngrySoundTech** [comment] 2016-08-27 00:15
It seems like this issue was fixed as of a4de667, as I am unable to recreate it with it. A new version has been submitted to CurseForge which will be the last update for 1.7.10, which contains a few small updates, and should correct this issue.

**Closed by AngrySoundTech** 2016-08-27 00:15 UTC
