### ISSUE TITLE
Wont detect blank record

### ISSUE THREAD

**Issue by Lucario17** [Stumblinbear/BetterRecords#42] opened 2017-12-22 00:28 UTC
When i try to etch a blank record in the record etcher with a valid dropbox .ogg file link and name it wint detect the blank record, im using better records 1.12.2 ver 1.5.0, released 4 days ago. the crystal tuner and radio work perfectly fine.
![screenshot 2017-12-22 00 25 18](https://user-images.githubusercontent.com/34756892/34280307-c9b43b7c-e6ae-11e7-8b0f-2f1eb63b7bc6.png)

**Comment by NicholasFeldman** [comment] 2017-12-22 00:55
Please provide forge version, as well as the URL being used

**Comment by Lucario17** [comment] 2017-12-22 00:56
Forge version: 14.23.1.2562
Link: https://www.dropbox.com/s/9s7sx4w38v051li/Red_Like_Roses.ogg?dl=1

**Comment by P3rf3ctXZer0** [comment] 2017-12-22 20:05
Oh my someone else with the same problem. I didn't bother reporting it because I knew they would figure it out eventually and last time I reported it I got scolded. At any rate I can confirm this bug does exist. Wondering if its related to dropbox since the user also the same file host.

**Comment by Lucario17** [comment] 2017-12-22 20:29
i have just used Onedrive as an alternative to dropbox and the error still appears so the file host isnt the issue, more likely its in the code for 1.12

**Comment by NicholasFeldman** [comment] 2017-12-22 20:35
More than likely it's an issue with the encoding of the file. The old error messages from before I took over the mod are very limited, and sometimes inaccurate. This is on my list for the next release. 

I'll take a look at this specific file when I get a chance, I'm away for the holidays taking some time off.

**Comment by Lucario17** [comment] 2017-12-22 20:36
take your time, and Happy Holidays.

**Comment by P3rf3ctXZer0** [comment] 2017-12-22 20:40
https://github.com/Stumblinbear/BetterRecords/issues/43

**Comment by Lucario17** [comment] 2017-12-22 20:45
doesn't happen with mine P3ft3ctXZer0, and im using over 200 other mods and im also on a custom server.(OPed as well)

**Comment by P3rf3ctXZer0** [comment] 2017-12-22 22:05
Watch video. @Lucario17

**Comment by NicholasFeldman** [comment] 2018-01-08 19:34
Looked into this more, and wrote up a document to help and address this. 

https://github.com/Stumblinbear/BetterRecords/wiki/Hosting-A-File-With-Dropbox

The issue here is you're trying to use `https://www.dropbox.com/s/9s7sx4w38v051li/Red_Like_Roses.ogg?dl=1`, when it should be`https://dl.dropboxusercontent.com/s/9s7sx4w38v051li/Red_Like_Roses.ogg?dl=1`

**Comment by NicholasFeldman** [comment] 2018-01-12 02:19
Closing, issue was likely solved with my last comment. Re-open if this persists.

**Closed by NicholasFeldman** 2018-01-12 02:19 UTC
Labels: Bug

**Comment by P3rf3ctXZer0** [comment] 2018-01-12 13:54
If you are going to close this issue I highly recommend you add this to the frontpage of your mod!

The issue here is you're trying to use https://www.dropbox.com/s/9s7sx4w38v051li/Red_Like_Roses.ogg?dl=1, when it should behttps://dl.dropboxusercontent.com/s/9s7sx4w38v051li/Red_Like_Roses.ogg?dl=1

Or else people will just reopen a similar issue!

@NicholasFeldman
