### ISSUE TITLE
Mekanism incompatibility ?

### ISSUE THREAD

**Issue by Ouack23** [Stumblinbear/BetterRecords#35] opened 2017-11-12 20:38 UTC
Hi, I'm having this error when launching minecraft 1.10.2 with BetterRecords-1.10.2-1.5.0-beta.3.jar

[https://pastebin.com/tWa111gT](https://pastebin.com/tWa111gT)

Whitout Better Records, the game works fine.
Java 1.8.151 x64 / Windows 10 64 bits / modlist in pastebin

Hope this helps,
Ouack23

**Comment by NicholasFeldman** [comment] 2017-11-12 20:49
Duplicate of #34, track this there.

**Closed by NicholasFeldman** 2017-11-12 20:49 UTC
Labels: Bug, Duplicate

**Comment by NicholasFeldman** [comment] 2017-11-12 23:49
The fix has been released, and is awaiting CurseForge's approval:
 https://minecraft.curseforge.com/projects/better-records/files/2499608
